// Action Types

export const TOGGLE_SHOW_STORIES = "TOGGLE_SHOW_STORIES";
export const SET_ACTIVE_STORIES_AND_INDEX = 'SET_ACTIVE_STORIES_AND_INDEX';
export const TOGGLE_MUTE = "TOGGLE_MUTE";
export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
export const SHOW_AND_SET_INDEX_FOR_ACTIVE_STORY =
  "SHOW_AND_SET_INDEX_FOR_ACTIVE_STORY";
export const SET_ZINDEX = "SET_ZINDEX";
export const SET_ACTIVE_STORIES_INDEX_ADN_SHOW =
  "SET_ACTIVE_STORIES_INDEX_ADN_SHOW";
